import type { Metadata } from 'next';
import { Lato } from 'next/font/google';
import './globals.css';
import { AppSidebar } from '@/components/app-sidebar';
import { SidebarProvider } from '@/components/ui/sidebar';
import Header from '@/components/header';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const lato = Lato({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className}`}>
        <SidebarProvider>
          <div className="flex h-full w-full">
            <AppSidebar />
            <div className="flex flex-col flex-1">
              <Header />
              <main className="flex-1 px-4 pb-8 max-w-7xl mx-auto w-full overflow-auto">
                {children}
              </main>
              <Toaster richColors />
            </div>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
